automation:
  - id: 'arrosage_zone_1'
    alias: Arrosage - Zone 1
    description: >-
      Lance un cycle d'arrosage de la zone 1.
      Si vous avez moins de 1 zones d'arrosage vous pouvez supprimer cette automatisation.
    triggers:
      - entity_id:
          - input_boolean.arrosage_auto_zone_1
        from: "off"
        to: "on"
        trigger: state
    conditions: []
    actions:
      - choose:
          - conditions:
              - condition: numeric_state
                entity_id: input_number.arrosage_electrovannes_incluses_zone_1
                below: 1
            sequence:
              - delay:
                  hours: 0
                  minutes: 0
                  seconds: 0
                  milliseconds: 500
              - action: input_boolean.turn_off
                metadata: {}
                data: {}
                target:
                  entity_id:
                    - input_boolean.arrosage_auto_zone_1
              - sequence:
                  - condition: state
                    entity_id: input_boolean.arrosage_enable_mobileapp_notifications
                    state: "on"
                  - action: script.envoi_notification_vers_mon_telephone
                    data:
                      message: >-
                        Le cycle d'arrosage de la zone {{
                        state_attr('sensor.arrosage_noms_des_zones', 'zone_1') }} ne
                        peut pas démarrer car aucune éléctrovanne n'est incluse dans
                        le cycle de la zone.
                      color: red
                      tag: arrosage
                      icon: mdi:sprinkler-variant
                      persistent: "true"
                alias: Notification application mobile
              - sequence:
                  - condition: state
                    entity_id: input_boolean.arrosage_enable_telegram_notifications
                    state: "on"
                  - action: telegram_bot.send_message
                    data:
                      title: >-
                        Arrosage - Problème
                      message: >-
                        Le cycle d'arrosage de la zone {{
                        state_attr('sensor.arrosage_noms_des_zones', 'zone_1') }} ne
                        peut pas démarrer car aucune éléctrovanne n'est incluse dans
                        le cycle de la zone.
                alias: Notification Télégram
          - conditions:
              - condition: state
                entity_id: binary_sensor.arrosage_electrovannes_connected
                state: "on"
            sequence:
              - sequence:
                  - condition: state
                    entity_id: input_boolean.arrosage_enable_mobileapp_notifications
                    state: "on"
                  - action: script.envoi_notification_vers_mon_telephone
                    data:
                      message: >-
                        Arrosage démarré {{ as_timestamp(now()) |
                        timestamp_custom('à %-H:%M') }}
                      title: "{{ state_attr('sensor.arrosage_noms_des_zones', 'zone_1') }}"
                      tag: arrosage zone 1
                      color: cyan
                      icon: mdi:sprinkler-variant
                      persistent: "true"
                alias: Notification application mobile
              - sequence:
                  - condition: state
                    entity_id: input_boolean.arrosage_enable_telegram_notifications
                    state: "on"
                  - action: telegram_bot.send_message
                    data:
                      message: >-
                        Arrosage démarré {{ as_timestamp(now()) |
                        timestamp_custom('à %-H:%M') }}
                      title: "Arrosage - {{ state_attr('sensor.arrosage_noms_des_zones', 'zone_1') }}"
                alias: Notification Télégram
              - action: input_datetime.set_datetime
                target:
                  entity_id: input_datetime.arrosage_duree_cycle_zone_1
                data:
                  timestamp: >-
                    {% set ns = namespace(duree = as_timestamp(now()) + 60) %} {%
                    for item in label_entities("Zone 1") | select('match',
                    'script.arrosage_declenchement_auto_voie') | sort %}
                      {% set ns.duree = ns.duree + (states('input_number.arrosage_duree_voie_' ~ item[-1]) | float) * (states('input_number.arrosage_coefficient_temps')|float) if is_state('input_boolean.arrosage_enable_voie_' ~ item[-1], 'on') else ns.duree %}
                    {% endfor %} {{ns.duree}}
              - repeat:
                  for_each: >-
                    {{ label_entities('Zone 1') | select('match',
                    'script.arrosage_declenchement_auto_voie') | sort }}
                  sequence:
                    - action: "{{repeat.item}}"
                      data: {}
              - action: input_boolean.turn_off
                metadata: {}
                data: {}
                target:
                  entity_id:
                    - input_boolean.arrosage_auto_zone_1
              - sequence:
                  - condition: state
                    entity_id: input_boolean.arrosage_enable_mobileapp_notifications
                    state: "on"
                  - action: script.envoi_notification_vers_mon_telephone
                    data:
                      message: clear_notification
                      tag: arrosage zone 1
                alias: Notification application mobile
              - sequence:
                  - condition: state
                    entity_id: input_boolean.arrosage_enable_telegram_notifications
                    state: "on"
                  - action: telegram_bot.send_message
                    data:
                      message: >-
                        Arrosage terminé {{ as_timestamp(now()) |
                        timestamp_custom('à %-H:%M') }}
                      title: "Arrosage - {{ state_attr('sensor.arrosage_noms_des_zones', 'zone_1') }}"
                alias: Notification Télégram
          - conditions:
              - condition: state
                entity_id: binary_sensor.arrosage_electrovannes_connected
                state: "off"
            sequence:
              - delay:
                  hours: 0
                  minutes: 0
                  seconds: 1
                  milliseconds: 0
              - action: input_boolean.turn_off
                metadata: {}
                data: {}
                target:
                  entity_id:
                    - input_boolean.arrosage_auto_zone_1
              - sequence:
                  - condition: state
                    entity_id: input_boolean.arrosage_enable_mobileapp_notifications
                    state: "on"
                  - action: script.envoi_notification_vers_mon_telephone
                    data:
                      message: >-
                        L'arrosage ne peut pas démarrer. Les programmateurs
                        d'arrosage ne sont pas connectés.
                      color: red
                      tag: arrosage
                      icon: mdi:sprinkler-variant
                      persistent: "true"
    mode: single